[project]
authors = ["Mehmet Efe Akça <efeakca@gmail.com>"]
channels = ["numba", "pytorch", "conda-forge"]
description = "Add a short description here"
name = "owl2vec_star"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
eval = "cd mmtf-eval && python embedding_evaluation.py"

[dependencies]
python = "==3.12.0"
jupyter = "==1.0.0"
rdflib = ">=4.2.2"
pyparsing = "==2.4.7"
scikit-learn = ">=1.5.2,<2"
nltk = "~=3.5"
owlready2 = ">=0.25"
pandas = ">=2.2.3,<3"
h5py = ">=3.12.1,<4"
matplotlib = ">=3.9.2,<4"
transformers = ">=4.46.2,<5"
tqdm = ">=4.67.0,<5"
pyyaml = ">=6.0.2,<7"
wandb = ">=0.18.5,<0.19"
rich = ">=13.9.4,<14"
seaborn = ">=0.13.2,<0.14"
numpy = "<2"
libblas = { version = "*", build = "*accelerate" }
scipy = "==1.13"
mpmath = ">=1.3.0,<2"
sympy = "==1.13.1"
numba = ">=0.60.0,<0.61"

[pypi-dependencies]
sentence-transformers = ">=3.3.0, <4"
torch = "==2.5.0"
torchvision = "==0.20.0"
torchaudio = "==2.5.0"
gensim = ">=4.3.2, <5"
cython = ">=3.0.11, <4"
pybind11 = ">=2.13.6, <3"
madbg = ">=1.3.2, <2"
